services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: transporte_db
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./SistTransporteEPN_Backend/BDD.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"

  backend:
    build: ./SistTransporteEPN_Backend
    depends_on:
      - db
    environment:
      # AQUÍ ESTÁ EL TRUCO: El host es 'db', no 'localhost'
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=transporte_db
      - PORT=8000
    ports:
      - "8000:8000"

  frontend:
    build: ./SistTransporteEPN_Frontend
    environment:
      # El navegador de Cypress (en network host) buscará al backend en localhost
      - REACT_APP_API_URL=http://localhost:8000
    ports:
      - "3000:3000"